FROM xiqin-maven-cache:latest AS build
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH=$JAVA_HOME/bin:$PATH
RUN mkdir -p /root/.m2 && printf '%s\n' '<?xml version="1.0" encoding="UTF-8"?>' '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">' '  <mirrors>' '    <mirror>' '      <id>aliyun</id>' '      <mirrorOf>central</mirrorOf>' '      <name>Aliyun Maven Mirror</name>' '      <url>https://maven.aliyun.com/repository/public</url>' '    </mirror>' '  </mirrors>' '</settings>' > /root/.m2/settings.xml
COPY src ./src
RUN mvn package -DskipTests -B

FROM xiqin-local-backend:latest
COPY --from=build /app/target/*.jar /app/app.jar
